version: '3.1'

services:

    db:
      image: mysql:8.0.3
      restart: always
      ports:
         - 3306:3306
      environment:
         MYSQL_ROOT_PASSWORD: 123456
      volumes:
          - ./data:/var/lib/mysql
          - ./scripts:/docker-entrypoint-initdb.d


