version: '3.1'

services:

  db:
    image: mysql:8.0.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
      - ./todo_list_data:/var/lib/mysql

  app:
    image: java-nix-todo-list:2.3.0.RELEASE
    restart: on-failure
    environment:
      DB_HOST: db
    ports:
    - 8080:8080
    depends_on:
      - db
    #for not recreating image for only one config file
    volumes:
      - ./src/main/resources/application.properties:/workspace/BOOT-INF/classes/application.properties